name: xiaohua_streamlit
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - intel-openmp=2022.0.0
  - joblib=1.1.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.2
  - liblapack=3.9.0
  - libzlib=1.2.11
  - mkl=2022.0.0
  - numpy=1.22.3
  - openssl=3.0.3
  - pip=22.1
  - python=3.10.4
  - python_abi=3.10
  - scikit-surprise=1.1.1
  - setuptools=62.2.0
  - six=1.16.0
  - sqlite=3.38.5
  - tbb=2021.5.0
  - tk=8.6.12
  - ucrt=10.0.20348.0
  - vc=14.2
  - vs2015_runtime=14.29.30037
  - wheel=0.37.1
  - xz=5.2.5
  - pip:
    - altair==4.2.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - attrs==21.4.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.0
    - blinker==1.4
    - cachetools==5.0.0
    - certifi==2021.10.8
    - cffi==1.15.0
    - charset-normalizer==2.0.12
    - click==8.0.4
    - colorama==0.4.4
    - debugpy==1.6.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - entrypoints==0.4
    - executing==0.8.3
    - fastjsonschema==2.15.3
    - gitdb==4.0.9
    - gitpython==3.1.27
    - idna==3.3
    - importlib-metadata==4.11.3
    - ipykernel==6.13.0
    - ipython==8.3.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.0
    - jedi==0.18.1
    - jinja2==3.1.2
    - jsonschema==4.5.1
    - jupyter-client==7.3.1
    - jupyter-core==4.10.0
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==1.1.0
    - markupsafe==2.1.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - nbclient==0.6.3
    - nbconvert==6.5.0
    - nbformat==5.4.0
    - nest-asyncio==1.5.5
    - notebook==6.4.11
    - packaging==21.3
    - pandas==1.4.2
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pickleshare==0.7.5
    - pillow==9.1.0
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.29
    - protobuf==3.20.1
    - psutil==5.9.0
    - pure-eval==0.2.2
    - pyarrow==8.0.0
    - pycparser==2.21
    - pydeck==0.7.1
    - pygments==2.12.0
    - pympler==1.0.1
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pytz-deprecation-shim==0.1.0.post0
    - pywin32==304
    - pywinpty==2.0.5
    - pyzmq==22.3.0
    - requests==2.27.1
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - semver==2.13.0
    - send2trash==1.8.0
    - smmap==5.0.0
    - soupsieve==2.3.2.post1
    - stack-data==0.2.0
    - streamlit==1.9.0
    - terminado==0.13.3
    - threadpoolctl==3.1.0
    - tinycss2==1.1.1
    - toml==0.10.2
    - toolz==0.11.2
    - tornado==6.1
    - traitlets==5.2.0
    - tzdata==2022.1
    - tzlocal==4.2
    - urllib3==1.26.9
    - validators==0.19.0
    - watchdog==2.1.7
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.6.0
    - zipp==3.8.0
prefix: C:\Users\xiao\anaconda3\envs\xiaohua_streamlit
